#!/bin/sh
SCGISTRING="setFooter(s);"
RCGISTRING="setFooter(s); var scriptpp = document.createElement(\\\\\"script\\\\\"); scriptpp.type = \\\\\"text/javascript\\\\\"; scriptpp.src = \\\\\"/addons/script/functions.js\\\\\"; \\\\\$(\\\\\"body\\\\\").appendChild(scriptpp);"

SCGISTRINGZWO="<td align='center' valign='middle'><div class='FooterButton' onclick='CollectData_SaveProfileSettings(0);'>\\\\\${footerBtnOk}</div></td>\\\\\";"
RCGISTRINGZWO="<td align='center' valign='middle'><div class='FooterButton' onclick='CollectData_SaveProfileSettings(0);'>\\\\\${footerBtnOk}</div></td><td align='center' valign='middle'><div class='FooterButton' onclick='PrintPage();'>Drucken</div></td>\\\\\";"

SDEVPARACGI="<td align='center' valign='middle'><div class='FooterButton' onclick='CloseDeviceParameters();'>\\\\\"+translateKey('footerBtnCancel')+\\\\\"</div></td>\\\\\";"
RDEVPARACGI="<td align='center' valign='middle'><div class='FooterButton' onclick='CloseDeviceParameters();'>\\\\\"+translateKey('footerBtnCancel')+\\\\\"</div></td><td align='center' valign='middle'><div class='FooterButton' onclick='PrintDevPara();'>Drucken</div></td>\\\\\";"

SPROGLISTSTRING="<td align='center' valign='middle'><div class='FooterButton CLASS04906' onclick='new HMScriptExecutor();' >\"+translateKey('footerBtnTestScript')+ \"</div></td>"
RPROGLISTSTRING="<td align='center' valign='middle'><div class='FooterButton CLASS04906' onclick='new HMScriptExecutor();' >\"+translateKey('footerBtnTestScript')+ \"</div></td><td align='center' valign='middle'><div class='FooterButton CLASS04905' onclick='PrintAllPrograms();'>alle Programme<br>drucken</div></td><td align='center' valign='middle'><div class='FooterButton CLASS04905' onclick='PrintAllSysPrograms();'>alle Programme inkl. <br>Systeminterne drucken</div></td>"

SSTRINGZWO="setFooter(s);"
RSTRINGZWO="setFooter(s); var scriptpp = document.createElement(\"script\"); scriptpp.type = \"text/javascript\"; scriptpp.src = \"/addons/script/functions.js\"; \$(\"body\").appendChild(scriptpp);"

SSTRING="<td align='center' valign='middle'><div class='FooterButton CLASS04801' onclick='new HMScriptExecutor();'>\${footerBtnTestScript}</div></td>"
RSTRING="<td align='center' valign='middle'><div class='FooterButton CLASS04801' onclick='new HMScriptExecutor();'>\${footerBtnTestScript}</div></td><td align='center' valign='middle'><div class='FooterButton' onclick='PrintPage();'>Drucken</div></td>"

case "$1" in
""|start)

      if [ -e /www/config/ic_deviceparameters.cgi_tmp ]; then
            echo "Temporary file /www/config/ic_deviceparameters.cgi_tmp does exist. Delete it..."
	     mount -o rw,remount /
	     rm -rf /www/config/ic_deviceparameters.cgi_tmp
	     mount -o ro,remount /
	  fi

	  if [ ! -e /www/config/ic_deviceparameters.cgi_org ]; then
            echo "File /www/config/ic_deviceparameters.cgi_org does not exist. Copying it..."
	     mount -o rw,remount /
	     mv /www/config/ic_deviceparameters.cgi /www/config/ic_deviceparameters.cgi_org
	     sed -e "s|$SCGISTRING|$RCGISTRING|g" "/www/config/ic_deviceparameters.cgi_org" > "/www/config/ic_deviceparameters.cgi_tmp"
	     sed -e "s|$SDEVPARACGI|$RDEVPARACGI|g" "/www/config/ic_deviceparameters.cgi_tmp" > "/www/config/ic_deviceparameters.cgi"
	     rm -rf /www/config/ic_deviceparameters.cgi_tmp
            chmod 755 /www/config/ic_deviceparameters.cgi
	     mount -o ro,remount /
	  fi

	  
	  if [ -e /www/config/ic_setprofiles.cgi_tmp ]; then
            echo "Temporary file /www/config/ic_setprofiles.cgi_tmp does exist. Delete it..."
	     mount -o rw,remount /
	     rm -rf /www/config/ic_setprofiles.cgi_tmp
	     mount -o ro,remount /
	  fi

	  if [ ! -e /www/config/ic_setprofiles.cgi_org ]; then
            echo "File /www/config/ic_setprofiles.cgi_org does not exist. Copying it..."
	     mount -o rw,remount /
	     mv /www/config/ic_setprofiles.cgi /www/config/ic_setprofiles.cgi_org
	     sed -e "s|$SCGISTRING|$RCGISTRING|g" "/www/config/ic_setprofiles.cgi_org" > "/www/config/ic_setprofiles.cgi_tmp"
	     sed -e "s|$SCGISTRINGZWO|$RCGISTRINGZWO|g" "/www/config/ic_setprofiles.cgi_tmp" > "/www/config/ic_setprofiles.cgi"
	     rm -rf /www/config/ic_setprofiles.cgi_tmp
            chmod 755 /www/config/ic_setprofiles.cgi
	     mount -o ro,remount /
	  fi

	  if [ -e /www/rega/pages/tabs/admin/views/programlist.htm_tmp ]; then
	     echo "Temporary file /www/rega/pages/tabs/admin/views/programlist.htm_tmp does exist. Delete it..."
	     mount -o rw,remount /
	     rm -rf /www/rega/pages/tabs/admin/views/programlist.htm_tmp
	     mount -o ro,remount /
	  fi

	  if [ ! -e /www/rega/pages/tabs/admin/views/programlist.org1 ]; then
	     echo "File /www/rega/pages/tabs/admin/views/programlist.org1 does not exist. Copying it..."
	     mount -o rw,remount /
	     mv /www/rega/pages/tabs/admin/views/programlist.htm /www/rega/pages/tabs/admin/views/programlist.org1
	     sed -e "s|$SPROGLISTSTRING|$RPROGLISTSTRING|g" "/www/rega/pages/tabs/admin/views/programlist.org1" > "/www/rega/pages/tabs/admin/views/programlist.htm_tmp"
	     sed -e "s|$SSTRINGZWO|$RSTRINGZWO|g" "/www/rega/pages/tabs/admin/views/programlist.htm_tmp" > "/www/rega/pages/tabs/admin/views/programlist.htm"
            chmod 755 /www/rega/pages/tabs/admin/views/programlist.htm
	     rm -rf /www/rega/pages/tabs/admin/views/programlist.htm_tmp
	     mount -o ro,remount /
	  fi

	  if [ -e /www/rega/pages/tabs/admin/views/programs.htm_tmp ]; then
	     echo "Temporary file /www/rega/pages/tabs/admin/views/programs.htm_tmp does exist. Delete it..."
	     mount -o rw,remount /
	     rm -rf /www/rega/pages/tabs/admin/views/programs.htm_tmp
	     mount -o ro,remount /
	  fi

	  if [ -e /www/rega/pages/tabs/admin/views/programs.org ]; then
	     echo "File /www/rega/pages/tabs/admin/views/programs.org does exist. Restore it..."
	     mount -o rw,remount /
	     rm -rf /www/rega/pages/tabs/admin/views/programs.htm
	     mv /www/rega/pages/tabs/admin/views/programs.org /www/rega/pages/tabs/admin/views/programs.htm
	     mount -o ro,remount /
	  fi

	  if [ ! -e /www/rega/pages/tabs/admin/views/programs.org1 ]; then
	     echo "File /www/rega/pages/tabs/admin/views/programs.org1 does not exist. Copying it..."
	     mount -o rw,remount /
	     mv /www/rega/pages/tabs/admin/views/programs.htm /www/rega/pages/tabs/admin/views/programs.org1
	     sed -e "s|$SSTRING|$RSTRING|g" "/www/rega/pages/tabs/admin/views/programs.org1" > "/www/rega/pages/tabs/admin/views/programs.htm_tmp"
	     sed -e "s|$SSTRINGZWO|$RSTRINGZWO|g" "/www/rega/pages/tabs/admin/views/programs.htm_tmp" > "/www/rega/pages/tabs/admin/views/programs.htm"
            chmod 755 /www/rega/pages/tabs/admin/views/programs.htm
	     rm -rf /www/rega/pages/tabs/admin/views/programs.htm_tmp
	     mount -o ro,remount /
	  fi

	  if [ ! -e /www/rega/esp/PrintPrograms.fn ]; then
	     echo "File /www/rega/esp/PrintPrograms.fn does not exist. Copying it..."
	     mount -o rw,remount /
	     cp /usr/local/etc/config/addons/www/script/PrintPrograms.fn /www/rega/esp/PrintPrograms.fn
            chmod 755 /www/rega/esp/PrintPrograms.fn
	     mount -o ro,remount /
	  fi

	  if [ ! -e /www/rega/esp/PrintProgram.htm ]; then
	     echo "File /www/rega/esp/PrintProgram.htm does not exist. Copying it..."
	     mount -o rw,remount /
	     cp /usr/local/etc/config/addons/www/script/PrintProgram.htm /www/rega/esp/PrintProgram.htm
            chmod 755 /www/rega/esp/PrintProgram.htm
	     mount -o ro,remount /
	  fi
		;;
	restart|stop)
		exit 0

		;;
	info)
		echo "Info: <center><b>Druck-Funktionen:</b></center>"
		echo "Info: <center>alle Programme (inkl. Systeminterne), einzelne Programme, Direkteverkn&uuml;pfungen, Ger&auml;teparameter, Gruppen-Einstellungen</center>"
    echo "Name: Programmedrucken CCU2"
    echo "Version: 1.1 modified by HMside"
    echo "Operations: uninstall"
    ;;
	uninstall)
		mount -o rw,remount /
		
	  if [ -e /www/rega/pages/tabs/admin/views/programs.org1 ]; then
			rm -rf /www/rega/pages/tabs/admin/views/programs.htm
			mv /www/rega/pages/tabs/admin/views/programs.org1 /www/rega/pages/tabs/admin/views/programs.htm
		fi
		
	  if [ -e /www/config/ic_deviceparameters.cgi_org ]; then
			rm -rf /www/config/ic_deviceparameters.cgi
			mv /www/config/ic_deviceparameters.cgi_org /www/config/ic_deviceparameters.cgi
		fi
		
	  if [ -e /www/config/ic_setprofiles.cgi_org ]; then
			rm -rf /www/config/ic_setprofiles.cgi
			mv /www/config/ic_setprofiles.cgi_org /www/config/ic_setprofiles.cgi
		fi

	  if [ -e /www/rega/pages/tabs/admin/views/programlist.org1 ]; then
			rm -rf /www/rega/pages/tabs/admin/views/programlist.htm
			mv /www/rega/pages/tabs/admin/views/programlist.org1 /www/rega/pages/tabs/admin/views/programlist.htm
		fi

		rm -rf /www/rega/esp/PrintPrograms.fn
		rm -rf /www/rega/esp/PrintProgram.htm
		rm -rf /etc/config/addons/www/script/
		rm -rf /mnt/etc/config/rc.d/programmedrucken
		mount -o ro,remount /
 		;;
	*)
        echo "Usage: programmedrucken {info|start|uninstall}" >&2
        exit 1
        ;; 

esac 

exit 0
		
